# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketHangOutPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroundName', models.CharField(blank=True, max_length=50, null=True)),
                ('AboutGround', models.CharField(blank=True, max_length=300, null=True)),
                ('Width', models.CharField(blank=True, max_length=50, null=True)),
                ('Length', models.CharField(blank=True, max_length=50, null=True)),
                ('TotalArea', models.CharField(blank=True, max_length=50, null=True)),
                ('PitchSize', models.CharField(blank=True, max_length=50, null=True)),
                ('NumberOfPitch', models.IntegerField(blank=True, null=True)),
                ('BallingMachin', models.BooleanField(default=False)),
                ('NetPractiseArea', models.CharField(blank=True, max_length=50, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
                ('AnyOtherInfo', models.CharField(blank=True, max_length=200, null=True)),
                ('SubsAndPacks', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HangOutPlaces',
            fields=[
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Area', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Website', models.CharField(blank=True, max_length=50, null=True)),
                ('PlaceId', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=20)),
                ('website', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crickethangoutplace',
            name='hangoutplaces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.HangOutPlaces'),
        ),
    ]
